### ISSUE TITLE
marking the title chunk as done during the publ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1520] opened 2016-05-25 20:23 UTC
Notes
======
marking the title chunk as done during the publish process. all others already marked.

Environment
======
Environment Key | Value
:----: | :----:
version | 8.0
build | 131
UDID | 3c7d0770c6265875
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | flo
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'int[] com.door43.translationstudio.core.Frame.getVerseRange()' on a null object reference
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter.onConfirmChunk(ReviewModeAdapter.java:1066)
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter.access$2400(ReviewModeAdapter.java:82)
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter$9$2.onClick(ReviewModeAdapter.java:647)
	at com.door43.translationstudio.dialogs.CustomAlertDialog$1.onClick(CustomAlertDialog.java:132)
	at android.view.View.performClick(View.java:4780)
	at android.view.View$PerformClick.run(View.java:19866)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```
Log history
======
```java
5/25/16 3:23 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:23 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:23 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:23 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:23 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:22 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:22 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:22 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_php_text_reg
5/25/16 3:17 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:17 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:969)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:932)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:17 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:16 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_ulb
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:15 PM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jud_text_reg
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:15 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:15 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation en-x-demo2_3jn_text_reg
5/25/16 3:15 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aaa_php_text_ulb
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:14 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:13 PM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jud_text_reg
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:13 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:13 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation en-x-demo2_3jn_text_reg
5/25/16 3:13 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aaa_php_text_ulb
5/25/16 3:12 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:12 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:12 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:12 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:958)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:921)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jud_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:11 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation en-x-demo2_3jn_text_reg
5/25/16 3:11 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jud_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:08 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:07 PM  E/com.door43.translationstudio.tasks.UpdateAppTask: Failed to commit migration changes to target translation en-x-demo1_jud_text_reg
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:07 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:07 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation en-x-demo2_3jn_text_reg
5/25/16 3:07 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation aaa_php_text_ulb
5/25/16 3:06 PM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:958)
	at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:921)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 6 more

5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo2_3jn_text_reg
5/25/16 3:06 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
     

```

**Comment by cckozie** [comment] 2016-05-25 20:28
Build 131
[en-x-demo2_php_text_reg_crash.tstudio.zip](https://github.com/unfoldingWord-dev/ts-android/files/282917/en-x-demo2_php_text_reg_crash.tstudio.zip)

**Comment by cckozie** [comment] 2016-05-25 20:42
This also happens when I attempt to mark the second chunk of any OBS story (the one that holds text like "A Bible story from:..." as done.

**Comment by neutrinog** [comment] 2016-05-25 21:17
duplicate of #1519

**Closed by neutrinog** 2016-05-25 21:17 UTC
Labels: 8.0, crash report, duplicate
