### ISSUE TITLE
trying to update source materials

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1354] opened 2016-03-19 02:52 UTC
Notes
======
trying to update source materials

Environment
======
Environment Key | Value
:----: | :----:
version | 3.3
build | 113
UDID | 42bd53508d26ee88
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Stack trace
======
```java
android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:742)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:892)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1686)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1632)
	at com.door43.translationstudio.core.IndexerSQLiteHelper.addProject(IndexerSQLiteHelper.java:131)
	at com.door43.translationstudio.core.Indexer.indexProjects(Indexer.java:173)
	at com.door43.translationstudio.core.Downloader.downloadProjectList(Downloader.java:117)
	at com.door43.translationstudio.core.Library.checkServerForUpdates(Library.java:133)
	at com.door43.translationstudio.tasks.GetLibraryUpdatesTask.start(GetLibraryUpdatesTask.java:22)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by neutrinog** [comment] 2016-03-24 21:06
duplicate of #1355

**Closed by neutrinog** 2016-03-24 21:06 UTC
Labels: 3.3, crash report, duplicate
