### ISSUE TITLE
just installed Travis build 1406 and clicked on the Info button on a project

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2152] opened 2017-04-12 14:45 UTC
Notes
======
just installed Travis build 1406

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 175
UDID | aec37215833e82ce
Android Release | 5.1.1
Android SDK | 22
Brand | Allwinner
Device | octopus-bt1077
Stack trace
======
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Dialog.setContentView(android.view.View)' on a null object reference
	at android.app.DialogFragment.onActivityCreated(DialogFragment.java:469)
	at android.app.Fragment.performActivityCreated(Fragment.java:2061)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:920)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:715)

```
Log history
======
```java
4/12/17 9:44 AM  W/TargetTranslationInfoDialog: Could not find source for target com.door43.translationstudio.core.TargetTranslation@24b75174
     

```

**Comment by cckozie** [comment] 2017-04-12 14:49
I can open the project but cannot open the Info menu.

**Comment by cckozie** [comment] 2017-04-12 15:06
It looks like this has been a problem on the NeuTab for a while. I installed a build from 4/3/17 and see the same problem.

**Comment by neutrinog** [comment] 2017-04-12 17:25
ok I think I fixed it. I can't reproduce but I did find a case where a null was returned erroneously.

**Comment by cckozie** [comment] 2017-04-17 16:37
Still failing on my NeuTab in Travis build 1412.

**Comment by neutrinog** [comment] 2017-04-20 00:06
@cckozie can  you send another crash report? I might have fixed the one above and you may be experiencing another issue.

**Comment by cckozie** [comment] 2017-04-20 13:10
See #2204

**Comment by cckozie** [comment] 2017-04-20 18:32
@neutrinog I renamed the tS folder and created a new project choosing target and source languages. Went to the home screen and clicked on the info button. App crashed as before.

**Comment by PhotoNomad0** [comment] 2017-04-20 19:12
@cckozie @neutrinog - cannot reproduce the info crash on my neutab for any of the projects here.  I am quite surprised that the current build is quite stable on this old device, but very slow and free memory gets very low at times.

**Comment by PhotoNomad0** [comment] 2017-04-20 19:14
I suggest we quirk it.  If we want to pursue it later, we need to come up with money to purchase another of these for development.

**Comment by neutrinog** [comment] 2017-04-20 20:58
I still cannot reproduce either.

**Comment by neutrinog** [comment] 2017-04-20 22:14
@cckozie shall we punt on this?

**Comment by cckozie** [comment] 2017-04-21 15:15
This appears to only be a problem on NeuTab devices running 5.1.1 so I'm going to close it pending feedback from the field.

**Closed by cckozie** 2017-04-21 15:15 UTC
Labels: 11.0, crash report, help wanted, QA Failed
