### ISSUE TITLE
Add Basic Search Ability

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-android#1321] opened 2016-03-03 20:20 UTC
See https://github.com/unfoldingWord-dev/ts-requirements/issues/26 for more details.

NOTE: This is basic search capability. More advanced features may be added at a later time.

**Comment by PhotoNomad0** [comment] 2016-09-15 14:41
Duplicate of https://github.com/unfoldingWord-dev/ts-android/issues/882.

**Closed** 2016-09-30 16:59 UTC
Labels: duplicate
