### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1351] opened 2016-03-18 10:38 UTC
Environment
======
Environment Key | Value
:----: | :----:
version | 5.0
build | 117
UDID | f97146a01c2c926
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Stack trace
======
```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.newui.translate.TargetTranslationActivity}: java.security.InvalidParameterException: a valid target translation id is required
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
	at android.app.ActivityThread.access$800(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.security.InvalidParameterException: a valid target translation id is required
	at com.door43.translationstudio.newui.translate.TargetTranslationActivity.onCreate(TargetTranslationActivity.java:78)
	at android.app.Activity.performCreate(Activity.java:5971)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 10 more

```
Log history
======
```java
3/17/16 4:03 PM  E/com.door43.translationstudio.newui.home.ImportDialog: Failed to import the archive
java.io.IOException: open failed: EBUSY (Device or resource busy)
	at java.io.File.createNewFile(File.java:941)
	at com.door43.util.Zip.unzipFromStream(Zip.java:343)
	at com.door43.translationstudio.core.Translator.importArchive(Translator.java:318)
	at com.door43.translationstudio.newui.home.ImportDialog.importUri(ImportDialog.java:221)
	at com.door43.translationstudio.newui.home.ImportDialog.onActivityResult(ImportDialog.java:179)
	at android.app.Activity.dispatchActivityResult(Activity.java:6177)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3737)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3784)
	at android.app.ActivityThread.access$1300(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at java.io.File.createNewFile(File.java:934)
	... 16 more

3/17/16 4:02 PM  E/com.door43.translationstudio.newui.home.ImportDialog: Failed to import the archive
java.io.IOException: open failed: EBUSY (Device or resource busy)
	at java.io.File.createNewFile(File.java:941)
	at com.door43.util.Zip.unzipFromStream(Zip.java:343)
	at com.door43.translationstudio.core.Translator.importArchive(Translator.java:318)
	at com.door43.translationstudio.newui.home.ImportDialog.importUri(ImportDialog.java:221)
	at com.door43.translationstudio.newui.home.ImportDialog.onActivityResult(ImportDialog.java:179)
	at android.app.Activity.dispatchActivityResult(Activity.java:6177)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3737)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3784)
	at android.app.ActivityThread.access$1300(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at java.io.File.createNewFile(File.java:934)
	... 16 more

3/17/16 4:00 PM  E/com.door43.translationstudio.tasks.CloneTargetTranslationTask: Failed to clone the repository gitolite3@ts.door43.org:tS/f97146a01c2c926/uw-tit-fr
org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /storage/emulated/0/translationStudio/translations/uw-tit-fr/.git failed
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:118)
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:161)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
	at com.door43.translationstudio.tasks.CloneTargetTranslationTask.onRegistered(CloneTargetTranslationTask.java:61)
	at com.door43.translationstudio.tasks.SshTask.start(SshTask.java:49)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: Creating directories for /storage/emulated/0/translationStudio/translations/uw-tit-fr/.git failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:316)
	at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:271)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:115)
	... 8 more

3/17/16 4:00 PM  E/com.door43.translationstudio.tasks.CloneTargetTranslationTask: Failed to clone the repository gitolite3@ts.door43.org:tS/f97146a01c2c926/uw-tit-fr
org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /storage/emulated/0/translationStudio/translations/uw-tit-fr/.git failed
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:118)
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:161)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
	at com.door43.translationstudio.tasks.CloneTargetTranslationTask.onRegistered(CloneTargetTranslationTask.java:61)
	at com.door43.translationstudio.tasks.SshTask.start(SshTask.java:49)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: Creating directories for /storage/emulated/0/translationStudio/translations/uw-tit-fr/.git failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:316)
	at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:271)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:115)
	... 8 more

3/17/16 3:59 PM  E/com.door43.translationstudio.newui.home.ImportDialog: Failed to import the archive
java.io.IOException: open failed: EBUSY (Device or resource busy)
	at java.io.File.createNewFile(File.java:941)
	at com.door43.util.Zip.unzipFromStream(Zip.java:343)
	at com.door43.translationstudio.core.Translator.importArchive(Translator.java:318)
	at com.door43.translationstudio.newui.home.ImportDialog.importUri(ImportDialog.java:221)
	at com.door43.translationstudio.newui.home.ImportDialog.onActivityResult(ImportDialog.java:179)
	at android.app.Activity.dispatchActivityResult(Activity.java:6177)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3737)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3784)
	at android.app.ActivityThread.access$1300(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5534)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: android.system.ErrnoException: open failed: EBUSY (Device or resource busy)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at java.io.File.createNewFile(File.java:934)
	... 16 more

     
```

**Comment by neutrinog** [comment] 2016-03-24 21:07
duplicate of #1352

**Closed by neutrinog** 2016-03-24 21:07 UTC
Labels: 5.0, crash report, duplicate
