### ISSUE TITLE
Import USFM Files

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-android#453] opened 2015-04-26 21:38 UTC
Related to #452, provide a method to import USFM files from zip file.  The USFM should be converted to USX and the \s 5 markers should be added based on the chunks.json files available in the api, e.g. https://api.unfoldingword.org/ts/txt/2/1jn/en/ulb/chunks.json.

Python is written for this at https://github.com/Door43/tools/blob/master/uwb/usfm_tS_import.py.

**Comment by ersimont** [comment] 2015-06-13 15:51
Is there any work in this direction yet?  If not, what level of effort would you estimate this at for an experienced Android programmer, and could I get some orientation to the relevant code before jumping in?

**Comment by neutrinog** [comment] 2015-06-18 16:07
The import/export has been in flux for some time so the code is not the prettiest. All the importing code is located in `com.door43.translationstudio.projects.Sharing`. I'd suggest starting by looking at the `importDokuWiki` method. The import methods are called from `com.door43.translationstudio.SharingActivity.importTranslation()`. This method determines what format is being imported and performs the correct operation.

**Comment by door43app** [comment] 2015-08-10 16:36
see `com.door32.translationstudio.projects.Sharing` in the `importDokuwiki` method for an example of how to save the imported content.

**Comment by neutrinog** [comment] 2016-02-10 20:23
importing details at https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation

**Comment by jag3773** [comment] 2016-02-11 22:31
Related to #1250

**Comment by neutrinog** [comment] 2016-05-10 16:55
duplicate of #1344

**Closed** 2016-05-10 16:55 UTC
Labels: duplicate
