### ISSUE TITLE
Done indicator in the blind draft mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/ts-android#873] opened 2015-10-09 12:42 UTC
When a chunk is labeled as "done", that chunk becomes un-editable in the "blind draft" mode. It was requested that there be some indicator on the blind draft indicating it was "done". This would help people to figure out why they can't edit that frame.

**Comment by neutrinog** [comment] 2015-10-26 16:46
@sampeckham could you provide some design suggestions?

**Comment by sampeckham** [comment] 2015-10-29 10:17
The metaphor that runs throughout is that anything with "note paper" is editable. When the chunk is marked as "Done" the note paper lines go away. Granted this is more subtle but it is learnable. 

Having seen the translators on the first version miss several times the indicator for adding verses, when it was right there, I would be more inclined to add feedback rather than another visual indicator. 

I suggest that the usual "tap" that would invoke edit mode, brings up a modal prompt "This chunk is marked as Done, editing is disabled." 

You could then prompt them to go to chunk mode and un-do the done status, or provide an option to undo it in the modal - which might be less frustrating and nicer.

**Comment by neutrinog** [comment] 2015-10-30 18:41
@PhotoNomad0 
In the dialog suggestion above use the text "This chunk is done. Continue editing?" with the options "Edit", and "Dismiss".

**Comment by PhotoNomad0** [comment] 2015-11-02 16:10
@neutrinog - Making sure I got this right.  I suppose this is to be added in holder.mTargetCard.setOnClickListener(new View.OnClickListener() within ChunkModeAdapter.  Is this the right place?

**Comment by neutrinog** [comment] 2015-11-08 23:30
@PhotoNomad0 yes that sounds correct.

**Comment by neutrinog** [comment] 2015-11-10 01:53
@PhotoNomad0 here's a sample of using a GestureDetector to detect a click

The detector
https://github.com/unfoldingWord-dev/ts-android/blob/develop/app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java#L484

Assigning it to a button
https://github.com/unfoldingWord-dev/ts-android/blob/develop/app/src/main/java/com/door43/translationstudio/newui/translate/ReviewModeAdapter.java#L525

**Comment by PhotoNomad0** [comment] 2015-11-10 21:05
@neutrinog - taking a look at it, but it looks like they are actually using setOnTouchListener() to capture events and using the detector to process the event.  I still cannot capture touch events once the target card moves to foreground.  I have tried setting listener on both the card and body, but they don't get called.  Looks like the issue is that if the edittext is not enabled, then the touch/focus/click events are blocked.  Doing some Googling, but so for none of the suggested work-arounds seem to work.

**Comment by PhotoNomad0** [comment] 2015-11-16 17:21
@neutrinog - think I figured out the difference.  I have been doing tapping on the target card to switch, but it looks like swiping gives the effect you are seeing.

**Closed** 2015-11-23 22:38 UTC
Labels: in review
