### ISSUE TITLE
obs upload test 2

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2217] opened 2017-04-24 16:59 UTC
Notes
======
obs upload test 2

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 175
UDID | a4b66484d349dee1
Android Release | 5.0.2
Android SDK | 21
Brand | lge
Device | e9wifi
Log history
======
```java
4/24/17 12:58 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:58 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:58 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:57 PM  W/com.door43.translationstudio.core.TargetTranslation: Unsupported target translation version 6 inen_obs_text_obs
4/24/17 12:56 PM  E/com.door43.translationstudio.tasks.PullTargetTranslationTask: git@git.door43.org:qa99/en_obs_text_obs.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: git@git.door43.org:qa99/en_obs_text_obs.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:261)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.pull(PullTargetTranslationTask.java:148)
	at com.door43.translationstudio.tasks.PullTargetTranslationTask.start(PullTargetTranslationTask.java:82)
	at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.eclipse.jgit.errors.TransportException: git@git.door43.org:qa99/en_obs_text_obs.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 7 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 14 more

4/21/17 6:01 PM  W/ImportUsfm: Warning: No chunk list found for 'ph'
4/21/17 5:57 PM  E/ImportUsfm: Error: Missing book name (\toc1)
4/21/17 5:57 PM  E/ImportUsfm: Error: Missing book short name (\id or \toc3)
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 21 to 999998 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 18 to 20 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 14 to 17 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 10 to 13 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 8 to 9 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 4 to 7 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: Missing chapter 4 - will try to recover
4/21/17 5:55 PM  W/ImportUsfm: missing chapter 4
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 20 to 999998 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 17 to 19 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 15 to 16 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 8 to 11 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 6 to 7 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 4 to 5 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: Missing chapter 3 - will try to recover
4/21/17 5:55 PM  W/ImportUsfm: missing chapter 3
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 19 to 21 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 17 to 18 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 14 to 16 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 12 to 13 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 5 to 8 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 3 to 4 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 1 to 2 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 20 to 21 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 18 to 19 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 15 to 17 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 7 to 8 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 3 to 6 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 21 to 999998 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 18 to 20 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 14 to 17 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 10 to 13 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 8 to 9 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 4 to 7 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 04
4/21/17 5:55 PM  W/ImportUsfm: Warning: Missing chapter 4 - will try to recover
4/21/17 5:55 PM  W/ImportUsfm: missing chapter 4
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 20 to 999998 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 17 to 19 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 15 to 16 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 8 to 11 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 6 to 7 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 4 to 5 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 03
4/21/17 5:55 PM  W/ImportUsfm: Warning: Missing chapter 3 - will try to recover
4/21/17 5:55 PM  W/ImportUsfm: missing chapter 3
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 19 to 21 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 17 to 18 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 14 to 16 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 12 to 13 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 5 to 8 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 3 to 4 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 1 to 2 in chapter: 02
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 20 to 21 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 18 to 19 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 15 to 17 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 01
4/21/17 5:55 PM  W/ImportUsfm: Warning: No verses in range 1 to 2 in chapter: 01
4/21/17 5:45 PM  E/WrapContentLinearLayoutManager: IndexOutOfBoundsException in RecyclerView is an Android bug
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{25ed0249 position=0 id=-1, oldPos=0, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
	at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5251)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5433)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
	at com.door43.translationstudio.ui.translate.WrapContentLinearLayoutManager.onLayoutChildren(WrapContentLinearLayoutManager.java:30)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3488)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 21 to 999998 in chapter: 04
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 18 to 20 in chapter: 04
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 14 to 17 in chapter: 04
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 10 to 13 in chapter: 04
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 8 to 9 in chapter: 04
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 4 to 7 in chapter: 04
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 04
4/21/17 5:45 PM  W/ImportUsfm: Warning: Missing chapter 4 - will try to recover
4/21/17 5:45 PM  W/ImportUsfm: missing chapter 4
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 20 to 999998 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 17 to 19 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 15 to 16 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 8 to 11 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 6 to 7 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 4 to 5 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 03
4/21/17 5:45 PM  W/ImportUsfm: Warning: Missing chapter 3 - will try to recover
4/21/17 5:45 PM  W/ImportUsfm: missing chapter 3
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 19 to 21 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 17 to 18 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 14 to 16 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 12 to 13 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 5 to 8 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 3 to 4 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 1 to 2 in chapter: 02
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 20 to 21 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 18 to 19 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 15 to 17 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 7 to 8 in chapter: 01
4/21/17 5:45 PM  W/ImportUsfm: Warning: No verses in range 3 to 6 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 21 to 999998 in chapter: 04
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 18 to 20 in chapter: 04
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 14 to 17 in chapter: 04
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 10 to 13 in chapter: 04
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 8 to 9 in chapter: 04
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 4 to 7 in chapter: 04
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 04
4/21/17 5:42 PM  W/ImportUsfm: Warning: Missing chapter 4 - will try to recover
4/21/17 5:42 PM  W/ImportUsfm: missing chapter 4
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 20 to 999998 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 17 to 19 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 15 to 16 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 8 to 11 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 6 to 7 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 4 to 5 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 1 to 3 in chapter: 03
4/21/17 5:42 PM  W/ImportUsfm: Warning: Missing chapter 3 - will try to recover
4/21/17 5:42 PM  W/ImportUsfm: missing chapter 3
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 19 to 21 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 17 to 18 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 14 to 16 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 12 to 13 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 5 to 8 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 3 to 4 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 1 to 2 in chapter: 02
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 28 to 999998 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 25 to 27 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 22 to 24 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 20 to 21 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 18 to 19 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 15 to 17 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 12 to 14 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 9 to 11 in chapter: 01
4/21/17 5:42 PM  W/ImportUsfm: Warning: No verses in range 1 to 2 in chapter: 01
     

```

**Comment by neutrinog** [comment] 2017-04-24 23:17
duplicate of #2218

**Closed by neutrinog** 2017-04-24 23:17 UTC
Labels: 11.0, bug report
