### ISSUE TITLE
changjng the keyboard by pressjng spacebar

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1091] opened 2015-12-09 15:24 UTC
Notes
======
changjng the keyboard by pressjng spacebar

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.2
build | 106
UDID | a640df0bc05dd5ec
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifi
Stack trace
======
```java
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:168)
	at com.door43.translationstudio.core.TargetTranslation$1.run(TargetTranslation.java:667)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /data/data/com.translationstudio.androidapp/files/translations/uw-mat-hi/.git/index
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
	at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
	at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1053)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
	... 2 more

```

**Comment by neutrinog** [comment] 2016-02-10 19:03
updated jgit in the hopes that this will be fixed. Cannot reproduce.

**Closed** 2016-02-10 19:03 UTC
Labels: 3.0.2, crash report
