### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1406] opened 2016-03-30 17:25 UTC
Environment
======
Environment Key | Value
:----: | :----:
version | 3.3
build | 113
UDID | ab5e9d6bc7ecc65b
Android Release | 4.2.2
Android SDK | 17
Brand | Lenovo
Device | A10
Stack trace
======
```java
java.lang.NullPointerException
	at com.door43.translationstudio.newui.translate.ReviewModeFragment$11.onPreprocess(ReviewModeFragment.java:487)
	at com.door43.translationstudio.rendering.HtmlRenderer.renderLink(HtmlRenderer.java:105)
	at com.door43.translationstudio.rendering.HtmlRenderer.renderPassageLink(HtmlRenderer.java:43)
	at com.door43.translationstudio.rendering.HtmlRenderer.render(HtmlRenderer.java:30)
	at com.door43.translationstudio.newui.translate.ReviewModeFragment.renderTranslationNote(ReviewModeFragment.java:519)
	at com.door43.translationstudio.newui.translate.ReviewModeFragment.onTranslationNoteClick(ReviewModeFragment.java:165)
	at com.door43.translationstudio.newui.translate.ReviewModeAdapter$20.onClick(ReviewModeAdapter.java:1305)
	at android.view.View.performClick(View.java:4207)
	at android.view.View$PerformClick.run(View.java:17358)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
3/30/16 8:24 PM  W/com.door43.translationstudio.spannables.PassageLinkSpan: invalid passage link address en:ta:vol1:translate:figs_rquestion
     
```

**Comment by neutrinog** [comment] 2016-03-30 23:42
duplicate of #1392

**Closed by neutrinog** 2016-03-30 23:42 UTC
Labels: 3.3, crash report
