### ISSUE TITLE
logging into door43

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1467] opened 2016-05-11 15:00 UTC
Notes
======
logging into door43

Environment
======
Environment Key | Value
:----: | :----:
version | 7.0
build | 128
UDID | 345d81bb2e44e64a
Android Release | 5.1.1
Android SDK | 22
Brand | google
Device | grouper
Stack trace
======
```java
java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.unfoldingword.gogsclient.User.fullName' on a null object reference
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:85)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
Log history
======
```java
5/11/16 11:00 AM  W/com.door43.translationstudio.tasks.LoginDoor43Task: gogs api responded with 401: null
java.io.FileNotFoundException: https://git.door43.org/api/v1/users/Chrisjarka/tokens
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:122)
	at org.unfoldingword.gogsclient.GogsAPI.request(GogsAPI.java:68)
	at org.unfoldingword.gogsclient.GogsAPI.createToken(GogsAPI.java:399)
	at com.door43.translationstudio.tasks.LoginDoor43Task.start(LoginDoor43Task.java:74)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

5/10/16 7:59 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/10/16 5:18 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/10/16 3:31 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation aa_rut_text_reg
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/10/16 2:40 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:263)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:233)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:228)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:115)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/9/16 12:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation fa_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/8/16 6:30 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation fa_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/8/16 1:51 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/8/16 7:21 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/8/16 6:16 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/8/16 12:25 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation aad_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/7/16 8:57 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation aad_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/7/16 6:33 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation fa_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/7/16 11:53 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation aad_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/7/16 10:10 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation aad_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/7/16 6:28 AM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/6/16 9:09 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/6/16 6:52 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation aad_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/6/16 6:52 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation fa_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/6/16 5:21 PM  E/com.door43.translationstudio.service.BackupService: Failed to backup the target translation en-x-demo2_obs_text_obs
java.lang.NullPointerException: Attempt to get length of null array
	at com.door43.util.Zip.zipSubFolder(Zip.java:217)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipSubFolder(Zip.java:219)
	at com.door43.util.Zip.zipToStream(Zip.java:149)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:248)
	at com.door43.translationstudio.core.Translator.exportArchive(Translator.java:218)
	at com.door43.translationstudio.AppContext.backupTargetTranslation(AppContext.java:218)
	at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:109)
	at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:29)
	at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:59)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

5/6/16 4:28 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
5/6/16 3:56 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
5/6/16 3:54 PM  W/com.door43.translationstudio.tasks.UpdateAppTask: Failed to migrate the target translation cache
     

```

**Comment by neutrinog** [comment] 2016-05-11 15:01
duplicate of #1464

**Closed by neutrinog** 2016-05-11 15:01 UTC
Labels: 7.0, crash report
