### ISSUE TITLE
Extra cards when in Project Review

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-android#1932] opened 2017-03-02 22:02 UTC
It looks like there are several extra cards displayed here. I don't know what they represent. It seems like it should be the same as it was in v9 with the new chapter title cards added. (V9 in last screen shot)

![screenshot_2017-03-02-15-55-57](https://cloud.githubusercontent.com/assets/8171759/23529016/7b3dce8e-ff61-11e6-8203-579d0145fc95.png)
![screenshot_2017-03-02-15-56-14](https://cloud.githubusercontent.com/assets/8171759/23529018/814a3bb4-ff61-11e6-9e7d-7cee07ee60c4.png)
![screenshot_2017-03-02-15-56-20](https://cloud.githubusercontent.com/assets/8171759/23529039/a0057db6-ff61-11e6-852e-efea0177f053.png)

V9
![screenshot_2017-03-02-15-45-40](https://cloud.githubusercontent.com/assets/8171759/23529058/af71bd32-ff61-11e6-8e33-a64294415ff3.png)

**Comment by PhotoNomad0** [comment] 2017-03-06 15:13
@cckozie - what project are you looking at?

**Comment by cckozie** [comment] 2017-03-06 15:34
@PhotoNomad0 Imported this usfm file
[php_usfm.usfm (1).zip](https://github.com/unfoldingWord-dev/ts-android/files/821598/php_usfm.usfm.1.zip)

**Comment by PhotoNomad0** [comment] 2017-03-06 17:59
@cckozie - cannot reproduce this problem.  Can you start with a fresh USFM import?  It smells like an old USFM import bug that should be fixed in the latest build.

**Comment by cckozie** [comment] 2017-03-06 18:20
@PhotoNomad0 It was a fresh import using the current build

**Comment by neutrinog** [comment] 2017-03-06 22:38
@cckozie I don't see those errors either. I do see one problem however. At the end of every chapter there is a "Philippians 2:" card.

![](mtp://[usb:003,002]/Internal%20storage/Pictures/Screenshots/Screenshot_2017-03-07-06-37-54.png)

**Comment by neutrinog** [comment] 2017-03-06 22:43
Also, we do display the chapter titles twice e.g. "chapter 3" then "chapter 3" again below it. That's because the first one is a summary, notice how the widths differ. Perhaps we could add some text to make it more clear what it is. e.g. "Chapter 3 has warnings".

**Comment by PhotoNomad0** [comment] 2017-03-07 16:31
> @cckozie I don't see those errors either. I do see one problem however. At the end of every chapter it gives a card with the chapter number and colon but no verse.

@neutrinog @cckozie  - I see the extra card at the end of the chapter sometimes.  It appears to be a double entry of the chapter title.  When chapter title is done it disappears.  Will take a look.

**Comment by cckozie** [comment] 2017-03-07 22:22
Still seeing an extra card at the end of most chapters and at the very end.
This project was a fresh import of a usfm file. I just added a chapter heading to chapter 1 and 2 and marked a couple chunks complete.
![screenshot_2017-03-07-16-05-03](https://cloud.githubusercontent.com/assets/8171759/23680676/b09144c8-0351-11e7-8dc5-6f841713bb53.png)

![screenshot_2017-03-07-16-19-46](https://cloud.githubusercontent.com/assets/8171759/23680789/1e834d14-0352-11e7-863e-61401cd164c0.png)

**Comment by PhotoNomad0** [comment] 2017-03-08 16:08
@cckozie - I grabbed the latest build from test fairy.  Notice a couple of things.
- it doesn't look like you have the latest build, because it adds the "has warnings" to chapter cards.
- I can still reproduce the bug that the book summary is at the front as well as the end.  Will fix that.

**Comment by PhotoNomad0** [comment] 2017-03-08 16:30
@cckozie - I would like to see that USFM file you are importing.  With the front matter chunk, I suspect it is corrupted due to some of our previous USFM import/export bugs.

**Comment by cckozie** [comment] 2017-03-08 16:55
@PhotoNomad0 Yes, the latest testing I did had the "has warnings" notice. I just didn't take another screen shot from that one since it was the same as before. Here's the file straight from the device (changed the extension).
[php_usfm.txt](https://github.com/unfoldingWord-dev/ts-android/files/828327/php_usfm.txt)

**Closed** 2017-06-13 00:12 UTC
Labels: QA Passed
