### ISSUE TITLE
I am running on Android 4.2.2.  \i just started...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1372] opened 2016-03-23 16:06 UTC
Notes
======
I am running on Android 4.2.2.  \i just started a translation and clicked "update library"  It told me "unfortunately translation Studio has stopped"

Environment
======
Environment Key | Value
:----: | :----:
version | 3.3
build | 113
UDID | f0f6686e75948219
Android Release | 4.2.2
Android SDK | 17
Brand | Lenovo
Device | A10
Stack trace
======
```java
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:727)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1565)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1514)
	at com.door43.translationstudio.core.IndexerSQLiteHelper.addProject(IndexerSQLiteHelper.java:131)
	at com.door43.translationstudio.core.Indexer.indexProjects(Indexer.java:173)
	at com.door43.translationstudio.core.Downloader.downloadProjectList(Downloader.java:117)
	at com.door43.translationstudio.core.Library.checkServerForUpdates(Library.java:133)
	at com.door43.translationstudio.tasks.GetLibraryUpdatesTask.start(GetLibraryUpdatesTask.java:22)
	at com.door43.util.tasks.ManagedTask.run(ManagedTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)

```

**Comment by neutrinog** [comment] 2016-03-24 21:04
duplicate of #1376

**Closed by neutrinog** 2016-03-24 21:04 UTC
Labels: 3.3, crash report, duplicate
