### ISSUE TITLE
Mode Icons not representing mode

### ISSUE THREAD

**Issue by sampeckham** [unfoldingWord-dev/ts-android#861] opened 2015-10-07 12:08 UTC
Checking mode icon does not change state and is always highlighted.

**Comment by neutrinog** [comment] 2015-10-14 18:58
we also need to update how modes are highlighted. The dark primary color beneath the white icon when selected should give a better contrast between selection states.

**Comment by jshuma** [comment] 2015-10-21 07:01
Sorry, I'm having trouble determining where to find this mode display in the app. Would you be able to give me some steps indicating how to get there?

**Comment by neutrinog** [comment] 2015-10-21 17:31
The code for handling/changing state of the different view modes is in `com.door43.translationstudio.newui.translate.TargetTranslationActivity` Take node of `mReadButton`, `mChunkButton`, and `mReviewButton`.

**Comment by neutrinog** [comment] 2015-10-23 05:38
@jshuma could you take out the left and right padding on the left toolbar so the button background spans from edge to edge?

Also, could we try out `R.color.primary_dark` for the background of selected buttons?

**Comment by jshuma** [comment] 2015-10-26 17:40
Added a [pull request](https://github.com/unfoldingWord-dev/ts-android/pull/929) for refinements. Tested on Nexus 4 and Nexus 10.

Here's before/after screen shots:
![before](https://cloud.githubusercontent.com/assets/7755451/10737145/de91a636-7bcd-11e5-8e83-0a09130d6c28.png)
![after](https://cloud.githubusercontent.com/assets/7755451/10737152/e22d330a-7bcd-11e5-87dc-fcab008670af.png)

**Comment by neutrinog** [comment] 2015-10-26 17:41
beautiful!

**Comment by jshuma** [comment] 2015-10-26 23:30
Closing since all related changes have been merged.

**Comment by sampeckham** [comment] 2015-11-04 11:40
Reopening as the original issue still remains.

See attached: I am in Read Mode (top icon) and yet the Check Mode (bottom icon) is still solid white. 

Lenovo Tab S8 / Android 4.4.2

![screen shot 2015-11-04 at 11 37 49](https://cloud.githubusercontent.com/assets/323212/10937091/865d7be4-82e8-11e5-8503-3a63257a68eb.png)

**Comment by jshuma** [comment] 2015-11-09 19:09
OK I think I've gotten to the bottom of the root cause here. Whereas the other buttons have their inactive state from dedicated icons (icon_frame_inactive.png and icon_study_inactive.png), the review mode button is computed from an XML file (ic_assignment_turned_in_inactive_24dp.xml) that attempts to derive from the graphic used for the active icon (ic_assignment_turned_in_white_24dp.png). The XML file applies a tint using android:tint, which corresponds to ImageView.setImageTintList() which was introduced in API 21, AKA Android 5.0. So in KitKat and earlier, that attribute is being ignored, and so it's being displayed as active. Since we need to support all the way back to API 15, this approach won't work.

I think the right fix here is to incorporate an icon for review mode with the inactive color baked in, just as with the other icons. However, I don't have any suitable software for making such an icon. @sampeckham, would you be able to create a new icon, derived from [the active version](https://github.com/unfoldingWord-dev/ts-android/blob/f0bb3ddf587005df13fe0968c3675cbc5642f2fe/app/src/main/res/drawable-hdpi/ic_assignment_turned_in_white_24dp.png), but tinted #B2DFD8? Or alternatively, do you have any suggestions for someone else I should contact for this?

**Comment by sampeckham** [comment] 2015-11-09 22:55
I'll get it to you tomorrow.

**Comment by sampeckham** [comment] 2015-11-10 13:56
Got these assets, I'll send over via Slack (can't do a zip here).

**Comment by neutrinog** [comment] 2015-11-11 22:04
related to https://github.com/unfoldingWord-dev/ts-android/issues/827

**Comment by sampeckham** [comment] 2016-02-02 16:35
This issues still persists in the latest build.

**Comment by neutrinog** [comment] 2016-02-10 18:42
we need to add colored resources for each state for full compatibility with older devices.

**Closed** 2016-02-18 22:38 UTC
Labels: bug, in progress
