### ISSUE TITLE
fails to render source

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#2036] opened 2017-03-23 18:22 UTC
Notes
======
fails to render source

Environment
======
Environment Key | Value
:----: | :----:
version | 11.0
build | 164
UDID | f710314c4d27668b
Android Release | 4.4.2
Android SDK | 19
Brand | rockchip
Device | rk292x
Log history
======
```java
3/23/17 2:20 PM  I/ViewModeFragment: doScrollToPosition: position=4, offset=0
3/23/17 2:19 PM  I/ViewModeFragment: doScrollToPosition: position=4, offset=0
3/23/17 2:19 PM  I/com.door43.translationstudio.services.BackupService: Backups running every 5 minute/s
3/23/17 2:19 PM  I/com.door43.translationstudio.services.BackupService: starting backup service
3/23/17 2:18 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 2:18 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/23/17 2:18 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 2:16 PM  I/ReviewModeAdapter: UI Miss: render_helps_01_07_task
3/23/17 2:13 PM  I/ReviewModeAdapter: UI Miss: render_source_01_07_task
3/23/17 2:13 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 2:13 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 2:08 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 2:08 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 2:03 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 2:03 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/23/17 2:03 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 2:03 PM  I/ReviewModeAdapter: Garbage collecting task: render_helps_01_09_task
3/23/17 2:03 PM  I/ReviewModeAdapter: Garbage collecting task: render_source_01_09_task
3/23/17 2:03 PM  I/ReviewModeAdapter: Garbage collecting task: render_helps_01_07_task
3/23/17 2:03 PM  I/ReviewModeAdapter: Garbage collecting task: render_source_01_07_task
3/23/17 2:03 PM  I/ViewModeFragment: doScrollToPosition: position=4, offset=0
3/23/17 2:03 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 2:02 PM  I/ReviewModeAdapter: UI Miss: render_source_01_07_task
3/23/17 2:02 PM  I/ReviewModeAdapter: UI Miss: render_source_01_title_task
3/23/17 2:02 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 2:02 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 2:02 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 2:02 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 2:01 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_ulb
3/23/17 2:01 PM  I/com.door43.translationstudio.ui.home.ImportFromDoor43Dialog: Repository cloned from https://git.door43.org/qa99/en-x-demo1_php_text_ulb
3/23/17 1:59 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 1:59 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 1:58 PM  I/ReviewModeAdapter: Garbage collecting task: render_helps_01_07_task
3/23/17 1:58 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 1:58 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/23/17 1:58 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 1:57 PM  I/ReviewModeAdapter: Garbage collecting task: render_helps_01_03_task
3/23/17 1:57 PM  I/ReviewModeAdapter: UI Miss: render_source_01_03_task
3/23/17 1:56 PM  I/ReviewModeAdapter: UI Miss: render_helps_01_07_task
3/23/17 1:53 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 1:53 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 1:53 PM  I/ReviewModeAdapter: UI Miss: render_source_01_07_task
3/23/17 1:53 PM  I/ReviewModeAdapter: UI Miss: render_source_01_title_task
3/23/17 1:53 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 1:53 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 1:53 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 1:53 PM  I/ViewModeFragment: doScrollToPosition: position=0, offset=0
3/23/17 1:53 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 1:53 PM  I/com.door43.translationstudio.services.BackupService: en-x-demo1_php_text_ulb backed up
3/23/17 1:53 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
3/23/17 1:53 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation en-x-demo1_php_text_ulb
3/23/17 1:53 PM  I/com.door43.translationstudio.ui.home.ImportFromDoor43Dialog: Repository cloned from https://git.door43.org/qa99/en-x-demo1_php_text_ulb
3/23/17 12:30 PM  I/com.door43.translationstudio.services.BackupService: Finished backup check.
3/23/17 12:29 PM  I/com.door43.translationstudio.services.BackupService: Checking for changes
     

```

**Comment by cckozie** [comment] 2017-03-23 18:28
I imported this project https://git.door43.org/qa99/en-x-demo1_php_text_ulb
I change the mode to only show chunks with conflicts
I waited for 10 minutes for the source to render. It did not. 
(screenshot after 10 minutes):
![screenshot_2017-03-23-14-13-33](https://cloud.githubusercontent.com/assets/8171759/24263807/4694dbe8-0fcc-11e7-983b-c84ea711a5a6.png)
I then changed to review mode, it scrolled to the top of the project. It did render the title and chapter 1 title after another 3 minutes.

**Comment by cckozie** [comment] 2017-03-23 19:00
It appears that this problem exists on all of my devices. Also tested on my phone, Lenovo, LG, and NeuTab. The source text for chunck 7 did not render after waiting 10 minutes on any of them. Interestingly, after the NeuTab went to sleep and I woke it up, the source did render. That was not the case on the other devices, but if I rotate them, then the source is rendered.

**Comment by neutrinog** [comment] 2017-03-23 21:38
duplicate of #2002

**Comment by cckozie** [comment] 2017-03-24 15:42
I agree that it's a dup of #2002 so I'm closing it.

**Closed by cckozie** 2017-03-24 15:42 UTC
Labels: 11.0, bug report, duplicate
