### ISSUE TITLE
This layout is wrapping the titles "Project" an...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#794] opened 2015-09-29 19:02 UTC
Notes
======
This layout is wrapping the titles "Project" and "Language Progress" where it looks funny and unreadable.

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 100
UDID | 7e2ee45fd76bb99
Android Release | 5.1
Android SDK | 22
Brand | google
Device | flo

**Comment by neutrinog** [comment] 2015-09-29 21:05
probably when vertical

**Comment by sampeckham** [comment] 2015-10-07 11:50
Duplicate of this issue: https://github.com/unfoldingWord-dev/ts-android/issues/761

**Closed** 2015-11-05 18:39 UTC
Labels: 3.0.0, bug report, duplicate
