### ISSUE TITLE
trying to exit the app. I was presented the dia...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1509] opened 2016-05-20 11:23 UTC
# Notes

trying to exit the app. I was presented the dialog verifying I wanted to exit, but after confirming it went back into the app. that happened twice. the third time it crashed.

Could there have been multiple instances of the app running? I remember that if I left the app without exiting and then clicked on the icon, it looked like it was spinning up a new instance rather than put me into the one already running.
# Environment

| Environment Key | Value |
| :-: | :-: |
| version | 8.0 |
| build | 129 |
| UDID | 3c7d0770c6265875 |
| Android Release | 5.1.1 |
| Android SDK | 22 |
| Brand | google |
| Device | flo |
# Stack trace

``` java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.translationstudio.androidapp/com.door43.translationstudio.newui.translate.TargetTranslationActivity}: java.security.InvalidParameterException: a valid target translation id is required
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
    at android.app.ActivityThread.access$800(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.security.InvalidParameterException: a valid target translation id is required
    at com.door43.translationstudio.newui.translate.ViewModeFragment.onCreateView(ViewModeFragment.java:70)
    at android.app.Fragment.performCreateView(Fragment.java:2053)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1869)
    at android.app.Activity.performCreateCommon(Activity.java:5985)
    at android.app.Activity.performCreate(Activity.java:5992)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
    ... 10 more

```
# Log history

``` java
5/20/16 6:21 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:21 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:21 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  E/TargetTranslationActivity: A valid target translation id is required. Received 'aaa_php_text_ulb' but the translation could not be found
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/en-x-demo1_jud_text_reg/.git/index
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:224)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:301)
    at org.eclipse.jgit.dircache.DirCache.lock(DirCache.java:267)
    at org.eclipse.jgit.lib.Repository.lockDirCache(Repository.java:1052)
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:142)
    ... 6 more

5/20/16 6:20 AM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aaa_php_text_ulb
5/20/16 6:20 AM  E/com.door43.translationstudio.service.BackupService: Failed to commit changes before backing up
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
    at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:212)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:963)
    at com.door43.translationstudio.core.TargetTranslation.commitSync(TargetTranslation.java:926)
    at com.door43.translationstudio.service.BackupService.runBackup(BackupService.java:106)
    at com.door43.translationstudio.service.BackupService.access$000(BackupService.java:32)
    at com.door43.translationstudio.service.BackupService$1.run(BackupService.java:63)
    at java.util.Timer$TimerImpl.run(Timer.java:284)
Caused by: org.eclipse.jgit.errors.LockFailedException: Cannot lock /storage/emulated/0/translationStudio/translations/aad_obs_text_obs/.git/index
    at org.eclip

```

**Comment by neutrinog** [comment] 2016-05-20 18:38
cannot reproduce app not exiting but I did update app to not crash in such a case.

**Comment by cckozie** [comment] 2016-05-23 20:32
I'm pretty sure there were multiple instances of the app running at the time. I can no longer reproduce this error, and now clicking on the app icon when it is already running always takes me into the running app.

**Comment by neutrinog** [comment] 2016-05-24 14:59
@cckozie FYI it's impossible for multiple versions of the *same* app to run at the same time in Android.

**Comment by cckozie** [comment] 2016-05-25 17:38
I ran into the appearance of this again today, although it no longer crashes. It may not be possible to have multiple instances of the same app "running", but it sure looks like there are. Here's how to reproduce that illusion:
1. uninstall tS
2. Install and open tS, logging in and agreeing.
3. Leave tS without closing it. (either switch to another app be using the square icon, or go to the home screen by using the circle icon)
4. Switch back to tS by clicking on its icon. You'll not that it's again going through the initialization/preparing process.
5. Click the triangle icon to exit and click Yes. You'll notice that it doesn't actually exit.
6. Click the triangle icon to exit and click Yes again, this time it will exit the app.
7. If steps 3 and 4 are repeated before going to step 5, then steps 5 and 6 will need to be repeated the same number of times. (just like there were multiple instances of the app running :)

**Comment by neutrinog** [comment] 2016-05-25 18:56
@cckozie I cannot reproduce this on any of my devices.

**Comment by cckozie** [comment] 2016-05-25 19:15
@neutrinog I see it every time on four of my devices, including the Lenovo and the LG. Did you follow my steps exactly, including step 1? It only happens after doing an install. After that it works as expected.

**Comment by neutrinog** [comment] 2016-05-26 00:10
ok I was able to reproduce it. Looking into it.

**Comment by cckozie** [comment] 2017-01-24 16:24
This issue is back again in V11 - 153. Again, it only is a problem when the app is first installed.

**Comment by neutrinog** [comment] 2017-02-03 23:18
@cckozie I cannot reproduce this issue (followed your steps exactly). What version of Android are you using?
I tested this on 4.4.4 and 5.0.1 and 6.0.1.

The app does not go through it's startup when re-opening it by clicking on the icon. And it does not re-open when I attempt to close it.

**Comment by neutrinog** [comment] 2017-02-03 23:29
nevermind. This issue only occurs when installing a release build. The development builds do not suffer from this.

**Comment by cckozie** [comment] 2017-02-06 18:57
In travis build 1123:
Upon installation, when I open the app and then go to the home page by clicking the circle icon, then click on the tS icon again, the app displays the "Welcome to translationStudio  performing updates" screen. This happens every time I execute that sequence until I exit the app using the back triangle icon. It is better now in that I only have to exit the app one time whereas before I had it to it as many times as I had opened the app using the tS icon. After the app is once exited then the behavior is as expected. I'm going to pass this for now and create a new issue in the backlog to clean up the "Welcome to..." screen when the app is still running.

**Closed** 2017-06-13 00:12 UTC
Labels: 8.0, 9.0, crash report, QA Passed
