### ISSUE TITLE
app is telling me that OBS is my only project c...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#1990] opened 2017-03-14 13:51 UTC
Notes
======
app is telling me that OBS is my only project choice no matter what language I choose.

Environment
======
Environment Key | Value
:----: | :----:
version | 9.0
build | 138
UDID | c5d305fe0643bc6e
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F
Log history
======
```java
3/14/17 9:28 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_obs_text_obs
3/14/17 9:28 PM  W/com.door43.translationstudio.core.TargetTranslation: Missing manifest file in target translation aa_obs_text_obs
     

```

**Comment by mondele** [comment] 2017-04-03 14:09
I wonder if this is related to the issue we have where translationStudio filters potential sources based upon localization of the tablet/app. Since many Gateway Languages are not yet available on Android, this causes unnecessary confusion for many users.

**Comment by cckozie** [comment] 2017-06-09 21:49
May be duplicate of #1567

**Comment by cckozie** [comment] 2017-06-09 21:53
dup

**Closed by cckozie** 2017-06-09 21:53 UTC
Labels: 9.0, bug report
