### ISSUE TITLE
When reviewing the frames in door43 to edit or ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-android#878] opened 2015-10-09 14:53 UTC
Notes
======
When reviewing the frames in door43 to edit or apply prior to the publish request, it would be helpful to have the original source text shown (below the picture perhaps), not just the last revision

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 104
UDID | fb2be1e70c7e5393
Android Release | 5.0.1
Android SDK | 21
Brand | Lenovo
Device | A10-70F

**Comment by neutrinog** [comment] 2015-10-14 18:52
@jag3773 This issue should be moved.

**Comment by jag3773** [comment] 2015-10-28 19:35
Duplicate of https://github.com/unfoldingWord-dev/Door43/issues/172

**Closed by jag3773** 2015-10-28 19:35 UTC
Labels: 3.0.0, bug report
